"""Item textures for the station recipes and their tools.

The two stews are vanilla's mushroom stew with the soup recoloured, so they sit next to vanilla
bowls. The rest is drawn here as 16x16 pixel maps.

    python3 tools/gen_recipe_textures.py <dir with vanilla textures/item>
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src/main/resources/assets/proficiency/textures/item")

PAL = {
    ".": None,
    "k": (24, 24, 24), "d": (68, 68, 68), "I": (150, 150, 150), "i": (216, 216, 216),
    "w": (137, 103, 39), "m": (104, 78, 30), "o": (40, 30, 11),
    "g": (252, 222, 80), "G": (200, 140, 20),
    "p": (236, 214, 160), "P": (212, 182, 124), "q": (160, 126, 76), "b": (96, 70, 36),
    "t": (214, 178, 110), "T": (184, 146, 80), "u": (140, 105, 55), "e": (70, 112, 40),
}

MAPS = {
"ladle": """
................
...........kkk..
..........kIiik.
.........kIiiIdk
.........kIiIIdk
..........kIddk.
.........kdkkk..
........kdk.....
.......kmk......
......kmk.......
.....kwk........
....kwk.........
...kwk..........
..kwmk..........
..kmk...........
...k............""",
"smithing_hammer": """
................
..kkkkkkkkkkk...
..kiiiiiiiiiik..
..kiIIIIIIIIdk..
..kiIIIIIIIIdk..
..kdddddddddk...
...kkkkmkkkk....
......kmk.......
.....kwk........
.....kwk........
....kwk.........
....kwk.........
...kwk..........
...kmk..........
..kmk...........
...k............""",
"butchers_cleaver": """
................
.....kkkkkkkkk..
....kiiiiiiiik..
....kiIIIIIkIk..
....kiIIIIIIIk..
....kiIIIIIIIk..
....kiIIIIIIdk..
....kddddddddk..
....kkmkkkkkk...
....kmk.........
...kwk..........
..kwk...........
..kwk...........
.kwk............
.kmk............
..k.............""",
"duelists_rapier": """
..............kk
.............kik
............kiIk
...........kiIk.
..........kiIk..
.........kiIk...
........kiIk....
.......kiIk.....
......kiIk......
..kk.kiIk.......
.kgGkiIk........
.kGgkIk.........
..kkmkgk........
...kmkGk........
..kmk.kk........
..kk............""",
"warriors_pierogi": """
................
................
................
................
.....bbbbb......
...bbpppppbb....
..bpppppppppb...
.bpppppPppppPb..
.bpppPPPpppPPb..
bPpPPPPPPPPPPPb.
bqPqPqPqPqPqPqb.
.bqbqbqbqbqbqb..
..b.b.b.b.b.b...
................
................
................""",
"trail_ration": """
................
................
................
................
....bbbbbbbbb...
...btttettttb...
..bttTTeTTTTtb..
..btTTTeTTTTub..
..beeeeeeeeeub..
..btTTTeTTTTub..
..btTTTeTTTuub..
..buuuueuuuuub..
...bbbbbbbbbb...
................
................
................""",
}

STEWS = {
    # light, mid, dark soup, then a few chunk pixels
    "miners_stew": [(206, 112, 58), (158, 70, 38), (92, 42, 20), (236, 200, 90)],
    "fishermans_chowder": [(240, 230, 204), (212, 196, 160), (150, 128, 96), (236, 130, 110)],
}


def draw(name, art):
    rows = [r for r in art.strip("\n").split("\n")]
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), name
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if PAL[ch]:
                im.putpixel((x, y), PAL[ch] + (255,))
    im.save(os.path.join(OUT, name + ".png"))


def stew(name, colours, vanilla):
    soup = Image.open(os.path.join(vanilla, "mushroom_stew.png")).convert("RGBA")
    bowl = Image.open(os.path.join(vanilla, "bowl.png")).convert("RGBA")
    out = soup.copy()
    n = 0
    for y in range(16):
        for x in range(16):
            px = soup.getpixel((x, y))
            if px == bowl.getpixel((x, y)):
                continue
            lum = sum(px[:3]) / 3
            colour = colours[0] if lum > 150 else colours[1] if lum > 80 else colours[2]
            if lum > 150:
                n += 1
                if n % 4 == 0:
                    colour = colours[3]
            out.putpixel((x, y), colour + (255,))
    out.save(os.path.join(OUT, name + ".png"))


if __name__ == "__main__":
    for name, art in MAPS.items():
        draw(name, art)
    for name, colours in STEWS.items():
        stew(name, colours, sys.argv[1])
    print("wrote", len(MAPS) + len(STEWS), "textures to", OUT)
