"""Generates TalentTable.java and the talent strings in en_us.json from talents_spec.py."""
import collections, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import talents_spec as spec

ROOT = os.path.dirname(HERE)
JAVA = os.path.join(ROOT, "src/main/java/dev/amman/proficiency/perk/TalentTable.java")
LANG = os.path.join(ROOT, "src/main/resources/assets/proficiency/lang/en_us.json")
FX = {"XP": "XP_RATE", "BON": "BONUS", "PC": "PROC_CHANCE", "PP": "PROC_POWER",
      "AD": "ABILITY_DURATION", "AC": "ABILITY_COOLDOWN", "DW": "DEATH_WARD", "TMP": "TEMPO"}


def kind(n):
    if n["row"] == 0:
        return "ROOT"
    if n["row"] == 5:
        return "CAPSTONE"
    if len(n["parents"]) >= 2 and n["ranks"] > 1:
        return "BRIDGE"
    if n["ranks"] == 1 and n["row"] >= 3:
        return "KEYSTONE"
    return "NODE"


def java_node(skill, n):
    fx = ", ".join(f"PerkEffect.{FX[k]}, {v}" for k, v in n["fx"].items())
    parents = ", ".join(f'"{p}"' for p in n["parents"])
    mat = f"m{n['mat']}" if n["mat"] else "List.of()"
    special = f'"{n["special"]}"' if n["special"] else "null"
    level = spec.LEVELS[n["row"]]
    return (f'                new Talent("{n["id"]}", skill, Kind.{kind(n)}, {n["row"]}, {n["col"]}, '
            f'{n["ranks"]}, {level}, {n["cost"]},\n'
            f'                        List.of({parents}), Map.of({fx}), {mat}, {special})')


def main():
    out = ["// GENERATED by tools/gen_talents.py from tools/talents_spec.py. Do not edit by hand.",
           "package dev.amman.proficiency.perk;", "",
           "import dev.amman.proficiency.perk.Talent.Kind;",
           "import dev.amman.proficiency.skill.Skill;", "",
           "import java.util.List;", "import java.util.Map;", "",
           "/** Every skill's own tree. The design lives in tools/talents_spec.py. */",
           "final class TalentTable {", "", "    private TalentTable() {", "    }", "",
           "    static List<Talent> nodes(Skill skill, List<Requirement> m1, List<Requirement> m2,",
           "            List<Requirement> m3, List<Requirement> m4) {",
           "        return switch (skill) {"]
    for skill, nodes in spec.TREES.items():
        out.append(f"            case {skill.upper()} -> List.of(")
        out.append(",\n".join(java_node(skill, n) for n in nodes) + ");")
    out += ["        };", "    }", "}", ""]
    open(JAVA, "w").write("\n".join(out))

    lang = json.load(open(LANG), object_pairs_hook=collections.OrderedDict)
    for key in [k for k in lang if k.startswith("proficiency.talent.") and not (
            k.startswith("proficiency.talent.msg.") or k.startswith("proficiency.talent.kind."))]:
        del lang[key]
    for key in [k for k in lang if k.startswith("proficiency.special.")]:
        del lang[key]
    for skill, nodes in spec.TREES.items():
        for n in nodes:
            lang[f"proficiency.talent.{skill}.{n['id']}"] = n["name"]
            lang[f"proficiency.talent.{skill}.{n['id']}.desc"] = n["desc"]
    json.dump(lang, open(LANG, "w"), ensure_ascii=False, indent=2)
    open(LANG, "a").write("\n")
    write_reference()
    print("wrote", JAVA, "and", sum(len(t) for t in spec.TREES.values()), "talents")


NAMES = {"XP": "XP", "BON": "passive", "PC": "signature chance", "PP": "signature power",
         "AD": "ability duration", "AC": "ability cooldown", "DW": "progress kept on death", "TMP": "tempo bonus"}
MAT = {1: "materials (old Apprentice list)", 2: "materials (old Journeyman list)",
       3: "materials (old Expert list)", 4: "materials (old Master list)"}


def write_reference():
    """docs/TREES.md: every tree, readable, from the same spec the code is built from."""
    lines = ["# Talent trees", "",
             "Generated by `tools/gen_talents.py` from `tools/talents_spec.py`. Do not edit by hand.", "",
             "Each rank costs the points shown. A node opens when every node it hangs from is full.",
             "Row levels: 0, 10, 30, 60, 90, 100. Every tree costs at most 100 points, which is what a",
             "level-100 skill earns, so every branch fills in the end.", ""]
    for skill, nodes in spec.TREES.items():
        cost = sum(n["ranks"] * n["cost"] for n in nodes)
        lines += [f"## {skill.capitalize()} ({cost} points)", ""]
        names = {n["id"]: n["name"] for n in nodes}
        for n in nodes:
            fx = ", ".join(f"{'+' if v > 0 else ''}{round(v * 100)}% {NAMES[k]}" + (" per rank" if n["ranks"] > 1 else "")
                           for k, v in n["fx"].items())
            extra = [x for x in [fx, MAT.get(n["mat"])] if x]
            after = f" (after {', '.join(names[p] for p in n['parents'])})" if n["parents"] else ""
            lines.append(f"- **{n['name']}** · {n['ranks']} rank{'s' if n['ranks'] > 1 else ''} · "
                         f"level {spec.LEVELS[n['row']]}{after}. {n['desc']}"
                         + (f" _{'; '.join(extra)}._" if extra else ""))
        lines.append("")
    os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
    open(os.path.join(ROOT, "docs/TREES.md"), "w").write("\n".join(lines))


main()
