"""16x16 skill icons in vanilla item style, one per skill.

Each icon is a hand-written pixel map below. The script adds the 1 px outline itself (any empty
pixel that touches a filled one on a side), so a map holds only the fill and any inner lines ('o').
Category colours come from SkillPalette.java and the skill list from Skill.java, so a new skill or a
changed colour shows up here on the next run.

    python3 tools/gen_skill_icons.py            # writes the PNGs
    python3 tools/gen_skill_icons.py --sheet out.png   # also a labelled 8x contact sheet

Rules for a new map: 16 rows of 16 characters, light from the top left, 3 to 4 shades per
material, no anti-aliasing. Letters 'A' 'a' 'b' 'c' are the skill's category colour (lightest to
darkest), so categories read as families.
"""
import os
import re
import sys

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA = os.path.join(ROOT, "src/main/java/dev/amman/proficiency")
OUT = os.path.join(ROOT, "src/main/resources/assets/proficiency/textures/gui/skill")


def hexrgb(v):
    return ((v >> 16) & 0xFF, (v >> 8) & 0xFF, v & 0xFF)


def mix(a, b, t):
    return tuple(round(a[i] * (1 - t) + b[i] * t) for i in range(3))


def read_categories():
    """skill id -> category name, and category name -> rgb, read from the Java sources."""
    skills = {}
    order = []
    with open(os.path.join(JAVA, "skill/Skill.java"), encoding="utf-8") as f:
        for m in re.finditer(r'^\s+[A-Z_]+\("([a-z_]+)", SkillCategory\.([A-Z_]+)', f.read(), re.M):
            skills[m.group(1)] = m.group(2)
            order.append(m.group(1))
    colours = {}
    with open(os.path.join(JAVA, "client/SkillPalette.java"), encoding="utf-8") as f:
        for m in re.finditer(r"case ([A-Z_]+) -> 0x[0-9A-Fa-f]{2}([0-9A-Fa-f]{6});", f.read()):
            colours[m.group(1)] = hexrgb(int(m.group(2), 16))
    return order, skills, colours


# Fixed materials. Each ramp runs light to dark.
BASE = {
    # iron
    "q": (236, 236, 236), "i": (196, 196, 196), "j": (138, 138, 138), "k": (88, 88, 92),
    # wood (handles, logs)
    "u": (176, 136, 82), "w": (134, 99, 56), "v": (96, 68, 36), "x": (66, 46, 24),
    # stone
    "s": (152, 152, 152), "t": (116, 116, 116), "y": (84, 84, 84),
    # gold
    "G": (255, 244, 140), "g": (242, 196, 60), "h": (178, 126, 32),
    # red
    "R": (236, 96, 80), "r": (186, 44, 36), "e": (120, 26, 22),
    # skin
    "p": (246, 206, 164), "P": (218, 166, 118), "n": (164, 112, 72),
    # water
    "5": (150, 214, 255), "6": (70, 150, 230), "7": (36, 88, 170), "8": (20, 50, 110),
    # dirt
    "d": (150, 104, 64), "E": (110, 74, 44),
    # wheat
    "Y": (246, 228, 120), "z": (214, 178, 62), "Z": (150, 116, 38),
    # leaf green
    "l": (120, 196, 80), "L": (64, 138, 46),
    # flame
    "f": (255, 210, 90), "F": (240, 128, 40),
    # white, bone, glass
    "W": (255, 255, 255), "O": (226, 222, 204), "N": (186, 178, 152),
    # near-black detail
    "X": (34, 30, 30),
    # dark blue/night
    "1": (60, 64, 96), "2": (36, 38, 62),
}

ICONS = {
"mining": """
................
....qqqqi.......
...qiiiiiij.....
........jiij....
.......uw..jij..
......uw....jij.
.....uw......jj.
....uw..........
...uw...........
..uw....sssssst.
.uw.....sAasbst.
.w......sbssAat.
........sssbbst.
........sAassst.
........tttttty.
................""",
"woodcutting": """
................
............uw..
...........uw...
..........uw....
.....iiq.uw.....
....qiiijw......
....qiiiij...l..
....qiijjw..lL..
..uuujjwwwwwwww.
.uwwujwvwwwvwww.
.uwuwuvwwvwwwvw.
.uwwuwwwvwwwvww.
..uuuvvvvvvvvvv.
................
................
................""","excavation": """
................
......uwwv......
......u..v......
.......uw.......
.......uw.......
.......uw.......
.......uw.......
.....qqiijj.....
.....qiiijj.....
.....qiiijj.....
......iijj......
...Aaa.ij.aaA...
..AdddddddddEa..
.AdddEddddddEEb.
.dddEdddddEddEE.
................""","farming": """
................
...Y....Y...Y...
..YzY..YzY.YzY..
..YzZ..YzZ.YzZ..
..zZY..zZY.zZY..
...zZ...zZ.zZ...
...Z.z..Z..Z....
....z.z.Z.Z.....
.....z.zZz......
......AaAb......
......abbc......
.....z.zZ.z.....
....z..zZ..z....
...z...zZ...z...
..Z....Z.Z...Z..
................""",
"fishing": """
.......k........
.......k........
.......k........
.......k........
.......k........
.......k........
.......k.j......
.......kkj......
..........aA....
....aaaAAAaaA..b
...aAAAAaaaabbab
..aAXAAaaaabb.bb
...abbbbbbbbbabb
....bbbcccbb...c
......cc........
................""",
"swords": """
................
.............qi.
............qij.
...........qij..
..........qij...
.........qij....
........qij.....
...b...qij......
...AbbqijX......
....ArrjX.......
.....Rrb........
....uwbAb.......
...uwX.Ab.......
..gwX...........
..gg............
................""",
"axes": """
................
...qi.....iq....
..qiij...jiiq...
..qiijjrjjiiq...
.qiijjjAjjjiiq..
.qiijjjajjjiij..
..qiij.u.jiij...
...ij..u..jj....
.......u........
.......w........
.......u........
.......w........
.......u........
.......w........
.......x........
................""",
"maces": """
................
...........j....
..........qii...
.........qiiij..
........jiiijjk.
.........ijjjk..
........aAjjk...
.......aA..k....
......uw........
.....uw.........
....uw..........
...uw...........
..uw............
..x.............
................
................""",
"tridents": """
................
....q...q...q...
....i...i...i...
....i...i...i...
....qi..i..qi...
....iiiiiiiii...
.....jjjijjj....
........i.......
........j.......
........A.......
........a.......
........b.......
........A.......
........a.......
........b.......
................""",
"unarmed": """
................
................
...pp.pp.pp.pp..
...pPnpPnpPnpP..
...pPnpPnpPnpP..
...PPnPPnPPnPP..
..ppppppppPnPP..
..pPPPPPPPPnPn..
..nnnnnnnnnPPn..
...PPPPPPPPPn...
....nnnnnnnn....
....AAAAAAAa....
....aaaaaaab....
....AAAAAAAa....
....bbbbbbbc....
................""","blocking": """
................
...uuuuuuuuuj...
..uqiiiiiiiijj..
..uiwwwAAwwwjj..
..uiwuwAAwuwjj..
..uiwwwAAwwwjj..
..uiAAAAAAAAjj..
..uiAAAAAAAAjj..
..uiwwwAAwwwjj..
..uiwuwAAwuwjj..
...uiwwAAwwjj...
...uijwAbwjjj...
....uijbbjjj....
.....ujjjjj.....
.......jj.......
................""",
"archery": """
................
.............q..
...Nuuuu....qi..
....N..uuw.ij...
.....N...uw.....
......N..wu.....
.......Nw..u....
.......wN..uw...
......w..N..u...
.....w....N.u...
....w......N.u..
..Aw........Nu..
.AwA.........u..
..a.............
................
................""",
"crossbows": """
................
.......q........
......qij.......
..q....w....j...
.qiiiiiwiiiiijk.
.qj...AwA....jk.
..NNNNNwNNNNNN..
......AwA.......
......uwv.......
......uwv.......
......uwvk......
......uwv.......
......uwv.......
......xxx.......
................
................""",
"endurance": """
................
................
...RRR...rrr....
..RWRRr.rrrre...
..RRRRrrrrrre...
..RRrrrrrrrre...
..rrrrrrrrrre...
...rrrrrrrre....
....rrrrrr..WW..
.....rrrr...WW..
......rr..WWWWWW
.......e..WWWWWW
............WW..
............WW..
................
................""",
"running": """
................
................
.....uuuu.......
.....uwwv.......
AAA..uwwv.......
.....uwwv.......
.aaa.uwwv.......
.....uwwvv......
AAA..uwwwwvv....
....uwwwwwwwv...
....uwwwwwwwwv..
....Aaaaaaaaaab.
....xxxxxxxxxxx.
................
................
................""","sneaking": """
................
......2222......
.....211112.....
....21111112....
...2111aa1112...
...211XXXX112...
..211XAXXAX112..
..21XXXXXXXX12..
..21XXXXXXXX12..
..211XXXXXX112..
..2111XXXX1112..
..21111111111...
..2111111111112.
..2111111111112.
..22222222222222
................""",
"jumping": """
................
.......A........
......AAa.......
.....AAaab......
....AAaaabb.....
.......ab.......
.......ab.......
.......ab.......
................
.....lllllll....
.....lLlLLLL....
.....ddddddE....
.....dEddEdE....
.....ddddEdE....
.....dEdddEE....
................""",
"swimming": """
................
................
.......5555.....
.....55666665...
....5667777665..
...566777..76...
...6677.....7...
..56777..5......
..6677..565...5.
.566777666665566
.667777777766677
.677777777777777
.777777777777777
................
................
................""",
"smithing": """
................
.......uw.......
.......uw.......
.......uw.......
.......uw.......
.......uw.......
..f..qqiiij..f..
.f...qiiijj...f.
..f..jjjjjk..f..
................
..qiiiiiiiiiij..
...jjjjjjjjjk...
....jjjiiijjk...
......jjjjk.....
....kkjjjjkkk...
................""","cooking": """
................
......O...O.....
.....O...O......
......O...O.....
................
...cccccccccc...
..cRRrrrrrrrec..
.kAAaaaaaaaabbk.
..Aaaaaaaaaabb..
..Aaaaaaaaabbb..
...abbbbbbbbc...
....cccccccc....
....f.FfF.f.....
....FfFfFfF.....
................
................""","alchemy": """
................
......vvv.......
......uwv.......
.......O........
......qOO.......
......qOO.......
.....qOOOO......
....qOOOOOO.....
...qAAAAAAaO....
...qAWAAaaab....
...OAAaaaabb....
...OaaaaabbbO...
....abbbbbbO....
.....OOOOOO.....
................
................""",
"masonry": """
................
................
................
....RRRrARRRr...
....rrrrArrrr...
....eeeeAeeee...
..AAAAAAAAAAAAA.
..RRrARRRrARRRr.
..rrrArrrrArrrr.
..eeeAeeeeAeeee.
.AAAAAAAAAAAAAA.
.RrARRRrARRRrAR.
.rrArrrrArrrrAr.
.eeAeeeeAeeeeAe.
................
................""","decorating": """
................
..hhhhhhhhhhhh..
..hggggggggggh..
..hg55555555Gh..
..hg5W555f55Gh..
..hg5555555lGh..
..hg555LLlllGh..
..hg5lllllLLGh..
..hgAAlLLLAAGh..
..hgaaAAAAabGh..
..hgGGGGGGGGGh..
..hhhhhhhhhhhh..
................
................
................
................""",
"spellcasting": """
................
..........G.....
..........G.....
........GGfGG...
.........GgG....
........G.g.G...
.......aA.......
......aA......b.
.....aA.....b...
....vu..........
...vu....a......
..vu............
..v.............
................
................
................""",
"engineering": """
................
.......ii.......
....j.qiij.j....
....iqiiiijj....
.....ijjjjj.....
..qiij.....jjj..
..qij..AA..jjk..
...ij.AabA.jk...
...ij.Abbb.jk...
..qij..bb..jkk..
..jjjj....jkkk..
.....jjjjjkk....
....jjjjjjkk....
....j.jkkk.k....
.......kk.......
................""",
"beastslaying": """
................
..AAaAAAaAAAb...
..Aaaaaaaaaab...
..abbbabbbabb...
..WO..WO..WO....
..WON.WON.WON...
...WO..WO..WO...
...WON.WON.WON..
....WO..WO..WO..
....ON..ON..ON..
.....N...N...N..
................
................
................
................
................""","wayfaring": """
................
.....AAAAAA.....
....AaqqqqaA....
...AaqqqqrqbA...
..Aaqqqqrrqqbb..
..aqqqqrrqqqqb..
..aqqqrrqqqqqb..
..aqqqXqqqqqqb..
..aqqqjjqqqqqb..
..aqqjjqqqqqqb..
..aqjjqqqqqqqb..
...bqqqqqqqqb...
....bbqqqqbb....
.....bbbbbb.....
................
................""",
"spelunking": """
................
.sstssttssstsst.
.sty...k.ty.sty.
..ty...k..y..ty.
..y...kkk....t..
.....kjjjk...y..
....jjjjjjj.....
....jfGGfFj.....
....jGGGfFj.....
....jfGfFFj.....
....jfFFFFj.....
....jjjjjjj.....
.....kkkkk......
................
................
................""","masonry2": None,
"social": """
................
.........pppp...
........pPPPPn..
...ppp..pXPXPn..
..pPPPn.pPPPPn..
..pXPXn.PnnnPn..
..pPPPn..nnnn...
..PnnnPnAAAAAa..
...nnnaAAaaaaab.
..AAAaaaaaaaaab.
.AAaaaabbaaaaab.
.Aaaaaabbbbbbbb.
.aaaaabb........
................
................
................""",
"nightwalker": """
................
.......AAAA.....
.....AAaa.......
....Aaaa......W.
...Aaab.........
...aaab.........
..Aaaab......W..
..aaabb.........
..aaabb.........
..aaabbb........
..baabbbb....AA.
...bbbbbbb...AA.
...cbbbbbbbbc...
....ccbbbbbcc...
......cccccc....
................""",
"courage": """
................
.uuuuuuuuuuuuuu.
.wwwwwwwwwwwwww.
..RRRRRRRRRRRr..
..RRRhghghRRrr..
..RRhghhhghRrr..
..RhgGGGGGghrr..
..RhGXGGGXGhrr..
..RgGGGeGGGgrr..
..RhGGrerGGhrr..
..RRhGGGGGhRrr..
..RRRhghghRRrr..
..RRRRRrRRRRrr..
..RRRrr.rrRrrr..
..RRr.....rrrr..
................""","guardian": """
................
..qqq..qq..qqj..
..qiiiiiiiiiij..
..qiRRRjjRRrij..
..qiRRRjjRRrij..
..qiRRRjjRRrij..
..qiRRqiijRrij..
..qiRRijjkRrij..
..qiRrrjjrrrij..
..qirrrjjrrrij..
..qirrrjjrrrij..
..qirrrjjrreij..
..qieeejjeeeij..
..qiiiiiiiiijj..
..jjjjjjjjjjjk..
................""","charger": """
................
................
................
................
AAAAA...qi......
........qiij....
........qiiiij..
.uuuuuuaqiiiiik.
.wwwwwwbjjjjjk..
........jjjk....
........jk......
.aaaaaa.........
................
AAAA............
................
................""","tactician": """
................
............Gg..
...........Gggh.
....RRRRRR..gh..
...RWWWWWWrj....
..RWrrrrrrkr....
.RWrWWWWWkrWr...
.RWrWrrrkWrWr...
.RWrWrkkrWrWr...
.RWrWrkkrWrWr...
.RWrWrrrrWrWr...
.RWrWWWWWWrWr...
..RWrrrrrrWr....
...rWWWWWWr.....
....rrrrrr......
................""",
}
ICONS.pop("masonry2")

# Colours that get no outline in one icon (thin lines like a fishing line or sparkles).
NO_OUTLINE = {"fishing": "k", "spellcasting": "Gfgab", "nightwalker": "W", "charger": "Aa",
              "cooking": "O", "running": "Aa", "smithing": "f", "maces": ""}


def palette(category_rgb):
    p = dict(BASE)
    p["A"] = mix(category_rgb, (255, 255, 255), 0.35)
    p["a"] = category_rgb
    p["b"] = mix(category_rgb, (0, 0, 0), 0.30)
    p["c"] = mix(category_rgb, (0, 0, 0), 0.55)
    p["o"] = mix(category_rgb, (16, 14, 14), 0.78)
    return p


def render(name, text, category_rgb):
    rows = text.strip("\n").split("\n")
    if len(rows) != 16 or any(len(r) != 16 for r in rows):
        raise SystemExit(f"{name}: map must be 16x16, got {[len(r) for r in rows]}")
    pal = palette(category_rgb)
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    bare = NO_OUTLINE.get(name, "")
    filled = [[ch != "." and ch not in bare for ch in row] for row in rows]
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == ".":
                continue
            if ch not in pal:
                raise SystemExit(f"{name}: unknown colour '{ch}' at {x},{y}")
            img.putpixel((x, y), pal[ch] + (255,))
    outline = pal["o"] + (255,)
    for y in range(16):
        for x in range(16):
            if rows[y][x] != ".":
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < 16 and 0 <= ny < 16 and filled[ny][nx]:
                    img.putpixel((x, y), outline)
                    break
    return img


def main():
    order, skills, colours = read_categories()
    missing = [s for s in order if s not in ICONS]
    extra = [s for s in ICONS if s not in skills]
    if missing or extra:
        raise SystemExit(f"missing icons {missing}, maps for unknown skills {extra}")
    os.makedirs(OUT, exist_ok=True)
    images = {}
    for sid in order:
        img = render(sid, ICONS[sid], colours[skills[sid]])
        img.save(os.path.join(OUT, sid + ".png"))
        images[sid] = img
    print(f"wrote {len(images)} icons to {OUT}")
    if "--sheet" in sys.argv:
        sheet(order, skills, images, sys.argv[sys.argv.index("--sheet") + 1])


def sheet(order, skills, images, path):
    """8x per icon plus 1x and 2x copies, on a mid grey and a dark tile, labelled."""
    cols = 6
    cw, ch = 220, 170
    rows = (len(order) + cols - 1) // cols
    out = Image.new("RGB", (cols * cw, rows * ch), (40, 42, 46))
    d = ImageDraw.Draw(out)
    for n, sid in enumerate(order):
        cx, cy = (n % cols) * cw, (n // cols) * ch
        d.rectangle([cx + 4, cy + 4, cx + 4 + 136, cy + 4 + 136], fill=(139, 139, 139))
        out.paste(images[sid].resize((128, 128), Image.NEAREST), (cx + 8, cy + 8), images[sid].resize((128, 128), Image.NEAREST))
        d.rectangle([cx + 146, cy + 8, cx + 146 + 40, cy + 8 + 60], fill=(24, 24, 28))
        out.paste(images[sid], (cx + 150, cy + 12), images[sid])
        big = images[sid].resize((32, 32), Image.NEAREST)
        out.paste(big, (cx + 150, cy + 32), big)
        d.text((cx + 8, cy + 146), f"{sid} ({skills[sid].lower()})", fill=(230, 230, 230))
    out.save(path)
    print("sheet", path)


if __name__ == "__main__":
    main()
